//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormulaServerServiceConsoleView.Service_References.FormulaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormulaServiceReference.IFormulaService")]
    public interface IFormulaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormulaService/GetCoreFPS", ReplyAction="http://tempuri.org/IFormulaService/GetCoreFPSResponse")]
        int GetCoreFPS();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormulaService/GetCoreFPS", ReplyAction="http://tempuri.org/IFormulaService/GetCoreFPSResponse")]
        System.Threading.Tasks.Task<int> GetCoreFPSAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormulaServiceChannel : IFormulaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormulaServiceClient : System.ServiceModel.ClientBase<IFormulaService>, IFormulaService {
        
        public FormulaServiceClient() {
        }
        
        public FormulaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormulaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetCoreFPS() {
            return base.Channel.GetCoreFPS();
        }
        
        public System.Threading.Tasks.Task<int> GetCoreFPSAsync() {
            return base.Channel.GetCoreFPSAsync();
        }
    }
}
