using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
namespace Regulus.Remote.Tools.Protocol.Sources
{
    public static class ClassDeclarationSyntaxExtensions
    {
        
        public static ClassDeclarationSyntax ImplementRegulusRemoteIGhost(this ClassDeclarationSyntax class_declaration)
        {
            var cd = class_declaration;
            var baseName = QualifiedName
                        (
                            QualifiedName(
                                IdentifierName("Regulus"),
                                IdentifierName("Remote")
                            )
                            .WithDotToken(
                                Token(SyntaxKind.DotToken)
                            ),
                            IdentifierName("IGhost")
                        );
            var type = SimpleBaseType(baseName);

            var baseList = cd.BaseList ?? SyntaxFactory.BaseList();

            var baseTypes = baseList.Types.ToArray();
            
            baseList = baseList.WithTypes(new SeparatedSyntaxList<BaseTypeSyntax>().Add(type).AddRange(baseTypes));
            cd = cd.WithBaseList(baseList);

            cd = cd.AddMembers(_CreateMembers(baseName, class_declaration.Identifier));
            

            return cd;
        }

        public static MemberDeclarationSyntax[] _CreateMembers(QualifiedNameSyntax base_name ,SyntaxToken name )
        {
            return new MemberDeclarationSyntax[]{
                    FieldDeclaration(
                        VariableDeclaration(
                            PredefinedType(
                                Token(SyntaxKind.BoolKeyword)
                            )
                        )
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier("_HaveReturn")
                                )
                            )
                        )
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.ReadOnlyKeyword)
                        )
                    ),
                    FieldDeclaration(
                        VariableDeclaration(
                            PredefinedType(
                                Token(SyntaxKind.LongKeyword)
                            )
                        )
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier("_GhostId")
                                )
                            )
                        )
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.ReadOnlyKeyword)
                        )
                    ),
                    ConstructorDeclaration(
                        name
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PublicKeyword)
                        )
                    )
                    .WithParameterList(
                        ParameterList(
                            SeparatedList<ParameterSyntax>(
                                new SyntaxNodeOrToken[]{
                                    Parameter(
                                        Identifier("id")
                                    )
                                    .WithType(
                                        PredefinedType(
                                            Token(SyntaxKind.LongKeyword)
                                        )
                                    ),
                                    Token(SyntaxKind.CommaToken),
                                    Parameter(
                                        Identifier("have_return")
                                    )
                                    .WithType(
                                        PredefinedType(
                                            Token(SyntaxKind.BoolKeyword)
                                        )
                                    )
                                }
                            )
                        )
                    )
                    .WithBody(
                        Block(
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName("_GhostId"),
                                    IdentifierName("id")
                                )
                            ),
                            ExpressionStatement(
                                AssignmentExpression(
                                    SyntaxKind.SimpleAssignmentExpression,
                                    IdentifierName("_HaveReturn"),
                                    IdentifierName("have_return")
                                )
                            )
                        )
                    ),
                    MethodDeclaration(
                        PredefinedType(
                            Token(SyntaxKind.LongKeyword)
                        ),
                        Identifier("GetID")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithBody(
                        Block(
                            SingletonList<StatementSyntax>(
                                ReturnStatement(
                                    IdentifierName("_GhostId")
                                )
                            )
                        )
                    ),
                    MethodDeclaration(
                        PredefinedType(
                            Token(SyntaxKind.BoolKeyword)
                        ),
                        Identifier("IsReturnType")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithBody(
                        Block(
                            SingletonList<StatementSyntax>(
                                ReturnStatement(
                                    IdentifierName("_HaveReturn")
                                )
                            )
                        )
                    ),
                    MethodDeclaration(
                        PredefinedType(
                            Token(SyntaxKind.ObjectKeyword)
                        ),
                        Identifier("GetInstance")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithBody(
                        Block(
                            SingletonList<StatementSyntax>(
                                ReturnStatement(
                                    ThisExpression()
                                )
                            )
                        )
                    ),
                    EventFieldDeclaration(
                        VariableDeclaration(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("Regulus"),
                                    IdentifierName("Remote")
                                ),
                                IdentifierName("CallMethodCallback")
                            )
                        )
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier("_CallMethodEvent")
                                )
                            )
                        )
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PrivateKeyword)
                        )
                    ),
                    EventDeclaration(
                        QualifiedName(
                            QualifiedName(
                                IdentifierName("Regulus"),
                                IdentifierName("Remote")
                            ),
                            IdentifierName("CallMethodCallback")
                        ),
                        Identifier("CallMethodEvent")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithAccessorList(
                        AccessorList(
                            List<AccessorDeclarationSyntax>(
                                new AccessorDeclarationSyntax[]{
                                    AccessorDeclaration(
                                        SyntaxKind.AddAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.AddAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_CallMethodEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    AccessorDeclaration(
                                        SyntaxKind.RemoveAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.SubtractAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_CallMethodEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    )
                                }
                            )
                        )
                    ),
                    EventFieldDeclaration(
                        VariableDeclaration(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("Regulus"),
                                    IdentifierName("Remote")
                                ),
                                IdentifierName("EventNotifyCallback")
                            )
                        )
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier("_AddEventEvent")
                                )
                            )
                        )
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PrivateKeyword)
                        )
                    ),
                    EventDeclaration(
                        QualifiedName(
                            QualifiedName(
                                IdentifierName("Regulus"),
                                IdentifierName("Remote")
                            ),
                            IdentifierName("EventNotifyCallback")
                        ),
                        Identifier("AddEventEvent")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithAccessorList(
                        AccessorList(
                            List<AccessorDeclarationSyntax>(
                                new AccessorDeclarationSyntax[]{
                                    AccessorDeclaration(
                                        SyntaxKind.AddAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.AddAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_AddEventEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    AccessorDeclaration(
                                        SyntaxKind.RemoveAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.SubtractAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_AddEventEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    )
                                }
                            )
                        )
                    ),
                    EventFieldDeclaration(
                        VariableDeclaration(
                            QualifiedName(
                                QualifiedName(
                                    IdentifierName("Regulus"),
                                    IdentifierName("Remote")
                                ),
                                IdentifierName("EventNotifyCallback")
                            )
                        )
                        .WithVariables(
                            SingletonSeparatedList<VariableDeclaratorSyntax>(
                                VariableDeclarator(
                                    Identifier("_RemoveEventEvent")
                                )
                            )
                        )
                    )
                    .WithModifiers(
                        TokenList(
                            Token(SyntaxKind.PrivateKeyword)
                        )
                    ),
                    EventDeclaration(
                        QualifiedName(
                            QualifiedName(
                                IdentifierName("Regulus"),
                                IdentifierName("Remote")
                            ),
                            IdentifierName("EventNotifyCallback")
                        ),
                        Identifier("RemoveEventEvent")
                    )
                    .WithExplicitInterfaceSpecifier(
                        ExplicitInterfaceSpecifier(
                            base_name
                        )
                    )
                    .WithAccessorList(
                        AccessorList(
                            List<AccessorDeclarationSyntax>(
                                new AccessorDeclarationSyntax[]{
                                    AccessorDeclaration(
                                        SyntaxKind.AddAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.AddAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_RemoveEventEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    AccessorDeclaration(
                                        SyntaxKind.RemoveAccessorDeclaration
                                    )
                                    .WithBody(
                                        Block(
                                            SingletonList<StatementSyntax>(
                                                ExpressionStatement(
                                                    AssignmentExpression(
                                                        SyntaxKind.SubtractAssignmentExpression,
                                                        MemberAccessExpression(
                                                            SyntaxKind.SimpleMemberAccessExpression,
                                                            ThisExpression(),
                                                            IdentifierName("_RemoveEventEvent")
                                                        ),
                                                        IdentifierName("value")
                                                    )
                                                )
                                            )
                                        )
                                    )
                                }
                            )
                        )
                    )
                };
        }

    }
}