// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace GameTest.ZsFormulaTest.DataTest
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class ZsFishStageDataCheckFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ZsFishStageDataCheck.feature"
#line hidden
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "ZsFishStageDataCheck", "In order to avoid silly mistakes\r\nAs a math idiot\r\nI want to be told the sum of t" +
                    "wo numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((TechTalk.SpecFlow.FeatureContext.Current != null) 
                        && (TechTalk.SpecFlow.FeatureContext.Current.FeatureInfo.Title != "ZsFishStageDataCheck")))
            {
                GameTest.ZsFormulaTest.DataTest.ZsFishStageDataCheckFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("取得0號魚場資料")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "ZsFishStageDataCheck")]
        public virtual void 取得0號魚場資料()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("取得0號魚場資料", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "StageId",
                        "Name",
                        "SizeType",
                        "BaseOdds",
                        "GameRate",
                        "MaxBet",
                        "NowBaseOdds",
                        "BaseChgOddsCnt"});
            table1.AddRow(new string[] {
                        "1",
                        "魚場1",
                        "SMALL",
                        "100",
                        "995",
                        "1000",
                        "0",
                        "0"});
            table1.AddRow(new string[] {
                        "2",
                        "魚場2",
                        "MEDIUM",
                        "200",
                        "995",
                        "1000",
                        "0",
                        "0"});
            table1.AddRow(new string[] {
                        "3",
                        "魚場3",
                        "MEDIUM",
                        "200",
                        "995",
                        "1000",
                        "0",
                        "0"});
            table1.AddRow(new string[] {
                        "4",
                        "魚場4",
                        "LARGE",
                        "300",
                        "995",
                        "1000",
                        "0",
                        "0"});
#line 8
 testRunner.Given("魚場資料表是", ((string)(null)), table1, "Given ");
#line 15
 testRunner.When("當輸入魚場id是 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "StageId",
                        "Name",
                        "SizeType",
                        "BaseOdds",
                        "GameRate",
                        "MaxBet",
                        "NowBaseOdds",
                        "BaseChgOddsCnt"});
            table2.AddRow(new string[] {
                        "1",
                        "魚場1",
                        "SMALL",
                        "100",
                        "995",
                        "1000",
                        "0",
                        "0"});
#line 17
 testRunner.Then("取得的魚場資料是", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
